---
name: Con Edison
version: dev
slug: coned_scraper
description: Con Edison account integration for Home Assistant â€” bills, payments, balance, MQTT
url: https://github.com/zodyking/HA-ConEd
ingress: true
ingress_port: 8000
panel_icon: mdi:flash
panel_admin: false
init: false
homeassistant: 2023.3.0
homeassistant_api: true
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
